[[redirects]]
  from = "/search"
  to = "https://bryan-madagan-stage.herokuapp.com"
  status = 301
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
