local_backend: true

backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: pages
    label: Page
    format: yml
    extension: yml
    folder: data/pages/
    create: true
    slug: '{{title}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Hero block
        name: hero_block
        widget: object
        fields:
          - label: Title
            name: title
            widget: string
          - label: Intro
            name: intro
            widget: text
          - label: Image
            name: image
            widget: image
            required: false
          - label: Button
            name: button
            widget: object
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: URL
                name: url
                widget: string
                required: false
          - label: Format
            name: format
            widget: select
            options: [
              "none",
              "header_1",
              "header_4",
              "header_6",
              "header_7",
              "header_8",
              "header_10",
              "header_11",
              "header_13",
              "header_15"
            ]
      - label: Blocks
        name: blocks
        widget: list
        types:
          - label: Content two column
            name: content_two_column
            widget: object
            fields:
              - label: Components
                name: components
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Intro
                    name: intro
                    widget: text
          - label: Grid 1
            name: grid_1
            widget: object
            fields:
              - label: Components
                name: components
                widget: list
                fields:
                  - label: Link
                    name: link
                    widget: object
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: URL
                        name: url
                        widget: string
                  - label: Image
                    name: image
                    widget: image
                    required: false
          - label: Grid 2
            name: grid_2
            widget: object
            fields:
              - label: Components
                name: components
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Image
                    name: image
                    widget: image
                    required: false
                  - label: Intro
                    name: intro
                    widget: text
                  - label: Link
                    name: link
                    widget: object
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: URL
                        name: url
                        widget: string
          - label: Grid 10
            name: grid_10
            widget: object
            fields:
              - label: Components
                name: components
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Intro
                    name: intro
                    widget: text
                  - label: Link
                    name: link
                    widget: object
                    fields:
                      - label: Title
                        name: title
                        widget: string
                      - label: URL
                        name: url
                        widget: string
          - label: Combo 4
            name: combo_4
            widget: object
            fields:
              - label: Components
                name: components
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Intro
                    name: intro
                    widget: text
                  - label: Icon number
                    name: icon_number
                    required: false
                    widget: string
          - label: Call To Action 1
            name: call_to_action_1
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Button
                name: button
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: URL
                    name: url
                    widget: string
              - label: Footer
                name: footer
                widget: string
          - label: Call To Action 2
            name: call_to_action_2
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Intro
                name: intro
                widget: text
              - label: Primary button
                name: primary_button
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: URL
                    name: url
                    widget: string
              - label: Secondary button
                name: secondary_button
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: URL
                    name: url
                    widget: string
          - label: Form 3
            name: form_3
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label: Intro
                name: intro
                widget: text

        
  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/units.yml
        label: Units
        name: units
        fields:
          - label: Currency
            name: currency
            widget: select
            options: ['€', '$', '£']
            default: '€'

          - label: Weight
            name: weight
            widget: select
            options: ['kg', ' st', ' lb']
            default: 'kg'
